# config/mongodb.yml
base: &base
  adapter: mongodb
  database: coolapp
#These are needed to authenticate with your db
#should it run on another server
  host: flame.mongohq.com
  port: 27059
  username: all41ofus_db
  password: Q^X,r%ZrFp,z%@!!!ju{j@8\3

development:
  <<: *base

test:
  <<: *base
  database: coolapp-test


production:
  <<: *base